#!/usr/bin/with-contenv bash

ARCH=$(uname -m)

if [ -f "/transmission-gluetun-port-update/transmission-gluetun-port-update_${ARCH}.tar.gz" ]; then
    echo "Installing transmission-gluetun-port-update"
    tar xf "/transmission-gluetun-port-update/transmission-gluetun-port-update_${ARCH}.tar.gz" -C /transmission-gluetun-port-update
    rm -rf \
        /transmission-gluetun-port-update/transmission-gluetun-port-update_x86_64.tar.gz \
        /transmission-gluetun-port-update/transmission-gluetun-port-update_aarch64.tar.gz
else
    echo "transmission-gluetun-port-update already installed, skipping"
fi

TRANSMISSION_USERNAME=$USER TRANSMISSION_PASSWORD=$PASS /transmission-gluetun-port-update/transmission-gluetun-port-update