name: Build on pull request

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}

jobs:
  pr:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        mod: ["transmission-gluetun-port-update"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2
        with:
          format: YYYYMMDDhhmmss

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get metadata for image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            michaukrieg/docker-mods
            ghcr.io/${{ github.repository }}
          tags: |
            ${{ matrix.mod }}
            ${{ matrix.mod }}-${{ steps.current-time.outputs.formattedTime }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.mod }}/Dockerfile
          context: ${{ matrix.mod }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
